seed: 1337

device: cuda:0

paths:
  data_path: /home/berkay/Desktop/research/datasets/NeoRadiumTDLdataset/train/TDLE/
  out_dir: runs/tdle_23/

split:
  val_split: 0.1

train:
  epochs: 3000
  batch_size: 64
  num_workers: 4

optim:
  lr: 1e-3
  weight_decay: 1e-5
  # AdamW + CosineAnnealingLR (paper)
  scheduler:
    t_max_epochs: 3000
    eta_min: 5e-5

early_stopping:
  patience: 3000
  min_delta: 1e-5

dataset:
  num_subcarriers: 120
  num_symbols: 14
  pilot_symbols: [2, 3]
  pilot_every_n: 2
  snrs: [0, 5, 10, 15, 20, 25, 30]

model:
  cnn_filters_1: 32
  cnn_filters_2: 2
  patch_h: 12
  patch_w: 14
  embed_dim: 64
  num_heads: 4
  dropout: 0.1
  kernel_size: 3

